### PR TITLE
Gg/devel

### PR DESCRIPTION
**Pull request by gggeek**
The base functionality is part of this first PR:
- upload of CRs
- search/browse for CRs
- a cli command to manage the users for the application

What's still missing:
- anti-csrf
- mandatory user log-in for the browsing interface
- upload rate-limiting
- self-service forgotpassword for app users

Notes:

The SQLite DB file and necessary tables are automatically created on access. I tested with the SQLite version used by PHP 8.1 on Ubuntu 22.04, but it should work with older versions too - the SQL used is very plain so far.

I set the min. required php version to 8.1, as found in eg. Ubuntu 22.04LTS. Bumping it to 8.3 would bring some nice goodies language-wise, but there are atm few LTS distros which ship it. WDYT?

The web interface is based on current Bootstrap, which allowed me to do basic styling and mobile/web support with minimal css/js development.

Sorry if you think this is going overboard with the framework-from-scratch development style. I tried to start out as simple as possible, but as soon as a couple of features got added, I found myself refactoring everything over and over until the code looked a lot like the patterns adopted by eg. Symfony. Still, the only external dependencies used so far are Twig and the Symfony Console (for its powerful capabilities of parsing cli options).

### CODE REVIEW

**Comment by gggeek** [comment]
ps: I forgot explaining a few details on the functionality:

- all CR fields are stored as plain text. I do not think any of those lends itself well to have a value taken from a limited list of values
- the search form uses the LIKE operator for all fields. This might not give the bestest perfs once the db is huge, but it allows to do smart searching with little effort
- atm the upload form is triggered by POST, but it will show the submitted data is a request is sent using GET fields. This allows end users to make a final decision before submitting the report, if the crash-reporting component of VC opens up their browser with link to the crash reporter. Otoh, sending a full stack trace via GET might not work too well, as any proxy/firewall in between VC and the site will most likely truncate the URL as it is too long - even the end user's browser might do that. I am not sure what is your vision about the interaction here: should the VC crash reporting component do the form submittal on its own?

**Comment by idrassi** [comment]
Thank you @gggeek for this amazing contribution!
I'm still reviewing your implementation. I have some remarks but I'll wait until I've completed the review and tests to provide full feedback.
Please allow me some time to get back to you.

**Comment by gggeek** [comment]
Btw, I have now completed work on adding

- mandatory login for the admin website
- self-service password change for logged-in users, with anti-csrf protection
- an audit log file to keep trace of user-related events and hacking attempts

The branch is visible at https://github.com/gggeek/VeraCrypt-CrashCollector/tree/gg/devel-access-control

I'll wait to create a PR until the review for this one is finished

**Comment by gggeek** [comment]
Hello again.

Today I have finished work on adding rate-limiting support.

The branch is visible at https://github.com/gggeek/VeraCrypt-CrashCollector/tree/gg/devel-rate-limiting. It supersedes the `devel-access-control` one, as it incorporates it.

The rate-limiting code is all built in-house, with no new requirements added to composer.json - it turned out that, by using Redis, it is dead simple to implement a fixed-window rate-limit algorithm :-)

Atm I have almost run out of work ;-) There are many small improvements I could pick up, but I'm not sure I should start working on them until the core has been validated...

**Comment by gggeek** [comment]
Hello.

Some more work has gone in: the latest "devel" branch has support for users resetting their password if they have forgotten it, without having to request the administrator to change it via the cli for them.

The code is in branch: https://github.com/gggeek/VeraCrypt-CrashCollector/tree/gg/devel-forgottenpassword

Did you have any time to continue the analysis of the PR?

**Comment by idrassi** [comment]
Thank you for the continued updates and for your patience.

I’ve run some tests, and functionally, everything is working well. I took extra time to review the code since I don’t have the same level of expertise as you. Honestly, the code is well-written and clean and I was able to clarify several points on my own after studying it.

Regarding the upload page: we should support only POST submissions without requiring any additional confirmation. However, one valuable feature would be to allow users to view the result of their submission and give them the option to delete it if they wish.
Do you think this can be implemented securely? We want to prevent attackers from brute-forcing the server to extract submitted reports.

One possible approach could be for the POST request to create a session token along with a report ID. These values (token and report ID) would be used by VeraCrypt to open a web page in the browser with a specific URL to view the report. The token would become invalid after, say, one hour. The page could also offer users the option to copy the report ID which they could then share via email or on a forum if they want to discuss the issue. On our side, the report ID would help us locate the user’s crash report.

What do you think?

In the meantime, I’ll merge this PR so you can create a new one with the finalized changes on top of it.

**Comment by idrassi** [comment]
I forgot: PHP 8.1 is good as this is what I have in the server currently.

**Comment by gggeek** [comment]
Thanks!

I will first send a new PR with the current tip of the development branches, then work on the feature you mentioned (allowing user to see their report, and be able to delete it) and submit a PR with that implementation.
The current development tip already has code for storage of one-time-use, time-limited access tokens, so it should be quite straightforward :-)

Just a question: I have implemented functionality for self-service password-reset by the "developer" team, ie. the users who will be able to see the reports. Atm, to keep the codebase lean, it relies on the php "mail" function call, which uses the system's sendmail setup under the hood, and is most often not the preferred choice for sending email via php. Is that ok? Would you rather use a php SMTP implementation, or maybe a http api call to a 3rd party email service?

**Pull request merged**
